Repository tinkerhub/saturday-hack-night, pull requests merged in 2023-02, with the labels that each got.

#45 fix: minor changes
  .env.example
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/event/event.service.ts
  apps/api/src/point/point.controller.ts
  apps/api/src/point/point.service.ts
  apps/shn-web/.env.example
  apps/shn-web/components/CampusLeaderboard.tsx
  apps/shn-web/components/EventCard.tsx
  apps/shn-web/components/UserLeaderboard.tsx
  apps/shn-web/package.json
  apps/shn-web/pages/_app.tsx
  apps/shn-web/pages/events.tsx
  apps/shn-web/public/images/seo-01.png
  tsconfig.json
  yarn.lock
Labels: bug

#46 fix: minor bugs
  apps/api/src/event/event.service.ts
  apps/shn-web/components/CurrentEvent.tsx
  apps/shn-web/types/index.ts
Labels: bug, enhancement, ui

#48 feat(web): added jest testing support , restructured folders in web codebase
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/test.yml
  apps/shn-web/__tests_/components/.gitkeep
  apps/shn-web/__tests_/pages/error.test.tsx
  apps/shn-web/__tests_/views/.gitkeep
  apps/shn-web/components/CurrentEvent.tsx
  apps/shn-web/components/ResultItems.tsx
  apps/shn-web/components/cards/Card.tsx
  apps/shn-web/components/cards/EventCard.tsx
  apps/shn-web/components/cards/index.ts
  apps/shn-web/components/index.ts
  apps/shn-web/components/modal/CreateTeamModal.tsx
  apps/shn-web/components/modal/ProfileModal.tsx
  apps/shn-web/components/modal/UpdateTeamModal.tsx
  apps/shn-web/components/utils/Accordion.tsx
  apps/shn-web/components/utils/LoadingAnimation.tsx
  apps/shn-web/components/utils/Toast.tsx
  apps/shn-web/components/utils/index.ts
  apps/shn-web/jest.config.js
  apps/shn-web/jest.setup.ts
  apps/shn-web/layouts/BaseLayout.tsx
  apps/shn-web/layouts/components/Footer.tsx
  apps/shn-web/layouts/components/MobileBar.tsx
  apps/shn-web/layouts/components/Navbar.tsx
  apps/shn-web/layouts/components/index.ts
  apps/shn-web/package.json
  apps/shn-web/pages/admin.tsx
  apps/shn-web/pages/auth.tsx
  apps/shn-web/pages/events.tsx
  apps/shn-web/pages/index.tsx
  apps/shn-web/public/js/squircle.js
  apps/shn-web/tsconfig.json
  apps/shn-web/utils/validators/index.ts
  apps/shn-web/utils/validators/profileValidator.ts
  apps/shn-web/utils/validators/teamValidator.ts
  yarn.lock
Labels: enhancement, ui
